In [1]:
import numpy as np

idades = np.array([10,15,20,18,20])

notas=np.array([9,8,5,7,10])

print(notas[idades==20]) #Imprimira 5 e 10 para idades = a 20

[ 5 10]


In [2]:
np.mean(idades) # média de idades

16.6

In [3]:
#                      func 1              func2            func3
salario = np.array([[1000, 1200, 1300],[800, 900, 1000],[2000,2100,2200]]) # Salario de 3 funcionarios em 3 anos seguidos

salario[1,2] # Salario do funcionario 2 no terceiro ano de trabalho

1000

In [4]:
matriz = np.zeros([4,3]) # Fa´ra uma matriz de 4 linhas e 3 colunas de zeros

print(matriz)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
